sms:
  suffix: lanbo11222334444
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dburl: jdbc:mysql://localhost:3306/sms_db
    username: root
    password: root
