sms:
  suffix: lanbo1122233
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dburl: jdbc:mysql://localhost:3306/sms_db2
    username: root
    password: root
